### ISSUE TITLE
A prompt before sending would be nise.

### ISSUE THREAD

**Issue by rohittp0** [cipherGUYS/SHN-Websocket#1]
Currently, the app is instantly sending what is in my clipboard to everyone in all rooms, this is a privacy concern so I would recommend you guys copy what is in the user's clipboard to the text box and send it only after the user presses send. 

And also the join room feature is a bit confusing, when I click on it it takes me to a random room. What exactly is the intended behavior? 

But overall loved the app, this is something I will use every day!

**Comment by mellofordev** [comment]
The room functionality is not supported at this time, and data is shared with all clients regardless of the rooms. We are adding a room function, so if you have the uid that the room creator will share with you—for example, u67c3—you can enter this uid, join that room and share clipboard data there.
You can see from the code that we hardcoded the room-id.A minor bug with rooms will be resolved right away.
I appreciate you giving it a try.

**Comment by mellofordev** [comment]
Im closing this issue as the room feature is fixed
